[project]
name = "Youtbe-downloader"
version = "0.1.0"
description = "A program to download YouTube videos at specified resolution"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "dotenv>=0.9.9",
    "load-dotenv>=0.1.0",
    "yt-dlp>=2025.7.21",
]
